# Generated by Django 3.2.4 on 2022-01-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=50, verbose_name='Status')),
                ('user_name', models.CharField(db_index=True, max_length=50, verbose_name='Username')),
                ('password', models.CharField(db_index=True, max_length=255, verbose_name='Password')),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True, verbose_name='Email')),
                ('token', models.CharField(max_length=500, verbose_name='Token')),
                ('token_expires_at', models.DateTimeField(max_length=50, verbose_name='Token Expires at')),
                ('role', models.CharField(choices=[('director', 'Director'), ('marketing', 'Marketing'), ('job_support', 'Job Support'), ('development', 'Development')], max_length=50, verbose_name='Role')),
                ('permission', models.CharField(choices=[('normal', 'Normal'), ('manager', 'Manager')], default='normal', max_length=50, verbose_name='Permission')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Datetime')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
