# Generated by Django 4.0.3 on 2022-10-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='permission',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('director', 'Director'), ('hr_level_1', 'HR Level 1'), ('hr_level_2', 'HR Level 2')], max_length=50, verbose_name='Role'),
        ),
    ]
