# Generated by Django 4.0.3 on 2022-10-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_permission_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Employee ID'),
        ),
    ]
