# Generated by Django 4.0.3 on 2022-10-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='', max_length=50, verbose_name='Status'),
        ),
    ]
