# Generated by Django 4.0.3 on 2022-10-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_date_of_birth_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('blank', ' '), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], max_length=50, verbose_name='Status'),
        ),
    ]
