# Generated by Django 4.0.3 on 2022-10-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_current_state_alter_lead_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Phone Number'),
        ),
    ]
