# Generated by Django 4.0.3 on 2022-10-13 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_employee_id'),
        ('leads', '0005_remove_lead_updated_by_alter_lead_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='calling_recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calling_recruiter', to='users.user'),
        ),
        migrations.AddField(
            model_name='lead',
            name='date_of_calling',
            field=models.DateTimeField(null=True, verbose_name='Date of Calling'),
        ),
        migrations.AddField(
            model_name='lead',
            name='liquidated_damage',
            field=models.CharField(choices=[('blank', ' '), ('yes', 'Yes'), ('no', 'No')], max_length=50, null=True, verbose_name='Liquidated Damage'),
        ),
        migrations.AddField(
            model_name='lead',
            name='night_shift',
            field=models.CharField(choices=[('blank', ' '), ('yes', 'Yes'), ('no', 'No')], max_length=50, null=True, verbose_name='Night Shift'),
        ),
        migrations.AddField(
            model_name='lead',
            name='relocate',
            field=models.CharField(choices=[('blank', ' '), ('yes', 'Yes'), ('no', 'No')], max_length=50, null=True, verbose_name='Relocate'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tutoring',
            field=models.CharField(choices=[('blank', ' '), ('yes', 'Yes'), ('no', 'No')], max_length=50, null=True, verbose_name='Tutoring'),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.AddField(
            model_name='lead',
            name='vocab_interview_date',
            field=models.DateTimeField(null=True, verbose_name='Interview Date'),
        ),
        migrations.AddField(
            model_name='lead',
            name='vocab_interview_result',
            field=models.CharField(choices=[('blank', ' '), ('qualified', 'Qualified'), ('not_qualified', 'Not Qualified'), ('rescheduled', 'Rescheduled'), ('not_attended', 'Not Attended')], max_length=50, null=True, verbose_name='Vocab Interview Result'),
        ),
        migrations.AddField(
            model_name='lead',
            name='vocab_interview_status',
            field=models.CharField(choices=[('blank', ' '), ('no pick up 1st', 'No Pick Up 1st'), ('no pick up 2nd', 'No Pick Up 2nd'), ('no pick up 3rd', 'No Pick Up 3rd'), ('declined', 'Declined'), ('will revert', 'Will Revert'), ('call later', 'Call Later'), ('rejected', 'Rejected'), ('interview_booked', 'Interview - Booked')], max_length=50, null=True, verbose_name='Vocab Interview Status'),
        ),
        migrations.AddField(
            model_name='lead',
            name='vocab_review',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Review'),
        ),
        migrations.AddField(
            model_name='lead',
            name='vocab_score',
            field=models.CharField(max_length=50, null=True, verbose_name='Vocab Score'),
        ),
        migrations.AddField(
            model_name='lead',
            name='wfo',
            field=models.CharField(choices=[('blank', ' '), ('yes', 'Yes'), ('no', 'No')], max_length=50, null=True, verbose_name='WFO'),
        ),
        migrations.AddField(
            model_name='lead',
            name='years_agreement',
            field=models.CharField(choices=[('blank', ' '), ('yes', 'Yes'), ('no', 'No')], max_length=50, null=True, verbose_name='2 Years Agreement'),
        ),
    ]
