# Generated by Django 4.0.3 on 2022-10-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_calling_recruiter_lead_date_of_calling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='communication_grade',
            field=models.CharField(choices=[('blank', ' '), ('a_good', 'A-Good'), ('b1_average', 'B1-Average'), ('b_fair', 'B-Fair'), ('c_below_average', 'C-Below Average')], max_length=50, null=True, verbose_name='Communication Grade'),
        ),
        migrations.AddField(
            model_name='lead',
            name='communication_interview_status',
            field=models.CharField(choices=[('blank', ' '), ('no pick up 1st', 'No Pick Up 1st'), ('no pick up 2nd', 'No Pick Up 2nd'), ('no pick up 3rd', 'No Pick Up 3rd'), ('declined', 'Declined'), ('will revert', 'Will Revert'), ('call later', 'Call Later'), ('rejected', 'Rejected'), ('interview_booked', 'Interview - Booked')], max_length=50, null=True, verbose_name='Communication Interview Status'),
        ),
        migrations.AddField(
            model_name='lead',
            name='communication_result',
            field=models.CharField(choices=[('blank', ' '), ('qualified', 'Qualified'), ('not_qualified', 'Not Qualified'), ('rescheduled', 'Rescheduled'), ('not_attended', 'Not Attended')], max_length=50, null=True, verbose_name='Communication Result'),
        ),
    ]
