# Generated by Django 4.0.3 on 2022-10-15 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_employee_id'),
        ('leads', '0008_lead_communication_interview_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='communication_calling_recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_calling_recruiter', to='users.user'),
        ),
        migrations.AddField(
            model_name='lead',
            name='communication_date_of_calling',
            field=models.DateTimeField(null=True, verbose_name='Date of Calling'),
        ),
        migrations.AddField(
            model_name='lead',
            name='communication_review',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Review'),
        ),
        migrations.AddField(
            model_name='lead',
            name='hr_calling_recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_calling_recruiter', to='users.user'),
        ),
        migrations.AddField(
            model_name='lead',
            name='hr_date_of_calling',
            field=models.DateField(null=True, verbose_name='Date of Calling'),
        ),
        migrations.AddField(
            model_name='lead',
            name='hr_interview_date',
            field=models.DateField(null=True, verbose_name='HR Interview Date'),
        ),
        migrations.AddField(
            model_name='lead',
            name='hr_interview_status',
            field=models.CharField(choices=[('blank', ' '), ('no pick up 1st', 'No Pick Up 1st'), ('no pick up 2nd', 'No Pick Up 2nd'), ('no pick up 3rd', 'No Pick Up 3rd'), ('declined', 'Declined'), ('will revert', 'Will Revert'), ('call later', 'Call Later'), ('rejected', 'Rejected'), ('interview_booked', 'Interview - Booked')], max_length=50, null=True, verbose_name='HR Interview Status'),
        ),
        migrations.AddField(
            model_name='lead',
            name='hr_result',
            field=models.CharField(choices=[('blank', ' '), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hold', 'Hold')], max_length=50, null=True, verbose_name='HR Result'),
        ),
        migrations.AddField(
            model_name='lead',
            name='hr_review',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Review'),
        ),
    ]
