# Generated by Django 4.0.3 on 2022-10-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_lead_communication_calling_recruiter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='hr_date_of_calling',
            field=models.DateTimeField(null=True, verbose_name='Date of Calling'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='hr_interview_date',
            field=models.DateTimeField(null=True, verbose_name='HR Interview Date'),
        ),
    ]
