# Generated by Django 4.0.3 on 2022-10-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_lead_follow_by_lead_joined_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='communication_interview_status',
            field=models.CharField(choices=[('blank', ' '), ('no_pick_up_1st', 'No Pick Up 1st'), ('no_pick_up_2nd', 'No Pick Up 2nd'), ('no_pick_up_3rd', 'No Pick Up 3rd'), ('declined', 'Declined'), ('will_revert', 'Will Revert'), ('call_later', 'Call Later'), ('rejected', 'Rejected'), ('interview_booked', 'Interview - Booked')], max_length=50, null=True, verbose_name='Communication Interview Status'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='hr_interview_status',
            field=models.CharField(choices=[('blank', ' '), ('no_pick_up_1st', 'No Pick Up 1st'), ('no_pick_up_2nd', 'No Pick Up 2nd'), ('no_pick_up_3rd', 'No Pick Up 3rd'), ('declined', 'Declined'), ('will_revert', 'Will Revert'), ('call_later', 'Call Later'), ('rejected', 'Rejected'), ('interview_booked', 'Interview - Booked')], max_length=50, null=True, verbose_name='HR Interview Status'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='joined_status',
            field=models.CharField(choices=[('blank', ' '), ('joined', 'Joined'), ('doj_extended', 'DOJ - Extended'), ('no_response', 'No Response'), ('yet_to_join', 'Yet to join'), ('declined', 'Declined'), ('joined_and_left', 'Joined & Left'), ('rejected_by_management', 'Rejected by Management')], max_length=50, null=True, verbose_name='Joined Status'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='offered_date_of_joining',
            field=models.DateTimeField(null=True, verbose_name='Date of Joining'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='revised_date_of_joining',
            field=models.DateTimeField(null=True, verbose_name='Revised Date of Joining'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='vocab_interview_status',
            field=models.CharField(choices=[('blank', ' '), ('no_pick_up_1st', 'No Pick Up 1st'), ('no_pick_up_2nd', 'No Pick Up 2nd'), ('no_pick_up_3rd', 'No Pick Up 3rd'), ('declined', 'Declined'), ('will_revert', 'Will Revert'), ('call_later', 'Call Later'), ('rejected', 'Rejected'), ('interview_booked', 'Interview - Booked')], max_length=50, null=True, verbose_name='Vocab Interview Status'),
        ),
    ]
