# Generated by Django 4.0.3 on 2022-10-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_alter_lead_communication_interview_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.IntegerField(db_index=True, max_length=50, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='year_of_graduation',
            field=models.IntegerField(max_length=50, verbose_name='Year of Graduation'),
        ),
    ]
