# Generated by Django 4.0.3 on 2022-10-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_alter_lead_phone_alter_lead_year_of_graduation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='year_of_graduation',
            field=models.IntegerField(verbose_name='Year of Graduation'),
        ),
    ]
