# Generated by Django 4.0.3 on 2022-10-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_alter_lead_phone_alter_lead_year_of_graduation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='updated_by',
        ),
    ]
